spring:
  application:
    name : book
  datasource:
    url: jdbc:mysql://localhost:3306/tendybook
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 10000
      idle-timeout: 60000
